version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true


linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goconst
    - gocyclo
    - misspell
    - bodyclose
    - copyloopvar
    - gosec
    - revive
  settings:
    govet:
      enable:
        - shadow
        - nilness
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 5
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: unused-parameter
          disabled: true
    gosec:
      excludes:
        - G124
        - G706

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - linters:
        - gosec
      text: "G124:"
